### ISSUE TITLE
please add support for underscore too

### ISSUE THREAD

**Issue by jabbalaci** [tov/thousands-rs#2]
Please add `num.separate_with_underscores()` too, for converting for instance `1234` to `1_234`. I know it could be done with a policy but a shortcut would be easier.

Rationale: you can also use `_` for literals, e.g. `let num = 1_234;` , so it seems obvious that we might want to see a number like this in a human-readable format.

**Comment by tov** [comment]
Sure, [here you go](https://github.com/tov/thousands-rs/releases/tag/0.1.3)!

**Comment by tov** [comment]
(Thanks for the suggestion.)
